### ISSUE TITLE
Use specified (external) directory for ROM storage / store ROMs outside of Gaseous application

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [gaseous-project/gaseous-server#101]
Right now, Gaseous requires importing of ROMs via UI or the Import directory.  ROMs are then processed and stored within Gaseous' application directory.

Feature request to have an option to point Gaseous to an external directory of existing ROMs and simply read them from there, rather than an 'import' process.

For example, I have an existing file share named "ROMs."  I want to be able to use that existing file share and have Gaseous simply read ROMs from there.  That way my ROM storage is accessible via both standard file share (in its existing folder structure) AND I have the benefit of using Gaseous as a ROM manager.

I have Gaseous stood up via Docker on X machine.  If I were to import my ROMs to Gaseous I'd have to have gigabytes, if not terabytes, of storage on machine X, as well as on machine Y that originally held my ROMs (and where I need to keep them in order to retrieve them without using Gaseous).

**Comment by TokugawaHeavyIndustries** [comment]
I will note that I'm working on understanding Gaseous' codebase in order to assist with this request... But at the same time, I have so many projects and so little time that I figured I'd ask for help via an issue haha

**Comment by michael-j-green** [comment]
I like this idea :) I've scheduled it for v1.7.0.

Looking forward to your notes if you get a look into the code... I'm a newbie when it comes to C# (yes, I started in VB, and been doing PowerShell for the last well, forever), so this is my first real project. I'm sure there's plenty of places to improve!

**Comment by TokugawaHeavyIndustries** [comment]
Haha I'm also a newbie with C#!  Last time I wrote in C# was probably a decade ago 👴
