### ISSUE TITLE
Generate Romset

### ISSUE THREAD

**Issue by SeeThruHead** [gaseous-project/gaseous-server#12]
**Is your feature request related to a problem? Please describe.**
I've always wanted a quick way to generate rom sets for different devices.
For instance some devices can only emulate a subset of my roms.
I want to generate a romset that will fill whatever sd card I have available but only using the best games from that system.

**Describe the solution you'd like**
Generate romset feature.
user will provide:
systems to be included
target romset size (sd card size)
a list of games that must be included in the romset
how much penalty will be given based on rom size
  (this is kind of difficult to pin down. but you may want to included less ps1 games since they are huge, compared to snes games, not sure what kind of toggle you would put here but maybe, prefer smaller games would give you more games in your romset but sacrifice the "rating" of the games overall a little)
  would be nice to download romset via the webapp in a zip file. OR output romset to a folder specified in the webui

**Describe alternatives you've considered**
building it myself lol

**Comment by michael-j-green** [comment]
Depends on #31

**Comment by michael-j-green** [comment]
@SeeThruHead; I'm about 2-3 days away from releasing v1.5.0 which will include this feature and wanted to give you a quick preview.

From the main screen clicking the "Collections" button will take you to this page:
<img width="1728" alt="Screenshot 2023-09-01 at 1 51 11 pm" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/9853b33e-7260-400d-891b-90714a377afc">
This page lists all of the saved collections. It ain't pretty, but here it is :) I'll circle back to the download link in a moment.

Clicking "New Collection" or "Edit" next to one of the items in the list will bring up this modal:
<img width="1728" alt="Screenshot 2023-09-01 at 1 51 23 pm" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/443612e1-7e36-4f38-863f-a275c5fd4da5">
Here you can set up your filters and settings to generate your romset - click Preview to update the content.

Once you click OK, the collection will be saved. In the background this will kick off a process that will build your collection into a zip file. The status of this process is displayed under the status column.

Once built, you can download the zip file with your roms in it by clicking the download button.

It should be noted that everytime the OK button is clicked on the collection editor modal will kick off a full rebuild of the zip file. This is also the only way to rebuild the zip from the UI at present.
