### ISSUE TITLE
MAME / Arcade Platform - Not recognised

### ISSUE THREAD

**Issue by kazjim** [gaseous-project/gaseous-server#125]
**Describe the bug**
All MAME Roms are identified as 'Unknown Platform'

**To Reproduce**
Import MAME ROMs
Attempt to build a collection
Cannot find Arcade / MAME as a platform

**Expected behavior**
MAME Roms would be identified as Arcade or MAME (or similar)

**Screenshots**
<img width="454" alt="image" src="https://github.com/gaseous-project/gaseous-server/assets/43019477/3469306b-27bb-4bf2-944d-8fcb705e5a8a">

**Desktop (please complete the following information):**
Mac Sonoma Beta 5

**Smartphone (please complete the following information):**
N/A

**Additional context**
May be a user error, but unsure.

**Comment by michael-j-green** [comment]
MAME/MESS DAT support is only added in v1.6.0 (in preview at the time of writing).

You can continue to import the MAME ROM's in the meantime though. They'll be marked in the database as not matched to a hash signature. This means that when you install v1.6.0, and add the DAT's, that the Library Scan background task will notice the unmatched ROM's and go about properly matching them.
