### ISSUE TITLE
When using the Upload Button, show a Green Check when import is completed

### ISSUE THREAD

**Issue by bullmoose20** [gaseous-project/gaseous-server#152]
**Is your feature request related to a problem? Please describe.**
WHen using the upload button, i drop files int here and there seems to be something happening, however more feedback to the user could be given... such as removing the upload from the box, or putting a big green checkmark when done. Also not clear what happens if you hit the "x" to close the upload modal when it has not finished processing the files.

**Describe the solution you'd like**
green check on all completed uploads with an exit button when things are completed.
Image below is showing after it was all uploaded but there is no real way to know... Maybe an upload report for the user telling them all were done or duplicates were found..or something...

![image](https://github.com/gaseous-project/gaseous-server/assets/12549033/4dc12400-16a3-460c-a9c0-3d6be0760141)

Here is one that is in progress. Notice how there is no real indicator of when it completes as it looks like the same as when you initially drop files in there (We see progress with the black bar that then turn clear again after it finishes):
![image](https://github.com/gaseous-project/gaseous-server/assets/12549033/55a5fe02-a755-484b-bafe-31e406a43f72)

**Comment by michael-j-green** [comment]
Thanks for your feedback!

Linking to existing issue: https://github.com/gaseous-project/gaseous-server/issues/73
