### ISSUE TITLE
Add totals found at the top right where games are found

### ISSUE THREAD

**Issue by bullmoose20** [gaseous-project/gaseous-server#201]
**Is your feature request related to a problem? Please describe.**
When filtering, it's not clear what the total number of games found is. 

**Describe the solution you'd like**
Any time a filter is applied, show the total number of games/records found in the window on the right, at the top. This way as you filter down from 1000s of games, you can see the results.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by michael-j-green** [comment]
Closed by #214
