### ISSUE TITLE
Improve filter section by implementing a search button

### ISSUE THREAD

**Issue by bullmoose20** [gaseous-project/gaseous-server#203]
**Is your feature request related to a problem? Please describe.**
When you have a large library and you are typing a search, I believe that each letter ends up submitting a request to filter. It makes the system react very slowly.

**Describe the solution you'd like**
Submit a search based on all criteria and in one "search" button... making it 1 sql query.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by michael-j-green** [comment]
There is supposed to be a 0.5 second delay when typing into the search box and the rating values box, that resets on each key up _before_ sending the request for the query results.

Might remove that in favour of a search button.

Are you happy for the checkbox based filters to be instant as they are now, or are you thinking to tie them to the search button too?

**Comment by bullmoose20** [comment]
> There is supposed to be a 0.5 second delay when typing into the search box and the rating values box, that resets on each key up _before_ sending the request for the query results.
> 
> Might remove that in favour of a search button.
> 
> Are you happy for the checkbox based filters to be instant as they are now, or are you thinking to tie them to the search button too?

I think it's best to put all that behind a search or show results button. No instant search as people might be selecting multiple radio buttons thus sending multiple queries for no reason.
