### ISSUE TITLE
Easier workflow for fixing matches

### ISSUE THREAD

**Issue by FlorianH1989** [gaseous-project/gaseous-server#25]
I am currently in the process of getting my title matchings right. Some of the roms are misinterpreted as NES, but in fact they are SNES. I wish for a batch processing setup where I can mark x numbers of roms and edit all the metadata in one go

Also typing in all the unknown titles one by one is a bite tedious. Maybe Gaseous can make a few suggested titles based on the file name. So you could fix a match just by clicking on the right title.

**Comment by michael-j-green** [comment]
This is a pain point for me too, thankyou for making a request for it.

In the meantime, you might have some better luck with auto matching if you import the SNES TOSEC DAT files into the /root/.gaseous-server/Data/Signatures/TOSEC folder. You can speed up the process by going to the cog in the top right and then running the "Signature Import" process.
<img width="1728" alt="Screenshot 2023-07-16 at 8 01 06 pm" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/20e6b8be-e2a3-4271-8f47-bea184743943">

Once it's imported the Library Scan process which runs every 30 minutes should notice the unknown files and hopefully match them based on the file hash.

In the coming days I'll add SNES to https://github.com/gaseous-project/gaseous-server/blob/main/gaseous-server/Support/PlatformMap.json which should help with matching. I need to add more platforms to this file.

**Comment by michael-j-green** [comment]
@FlorianH1989; I've just committed PR #28 which includes better SNES handling.

Once the docker image is updated, Gaseous should better automatch your SNES titles.

Note that your other request for easier/bulk manual matching is still in the works, so this issue will remain open until then.

**Comment by FlorianH1989** [comment]
Hey this worked for me! All my SNES Games are now matched. 

Unfortunately the "Start" Button stopped working. Even for N64 Games which worked before. The "Start" button opens a dropdown menu where I can choose firmwares. But I am not able to choose anything. 

Should I open a new issue for this?
<img width="828" alt="Bildschirmfoto 2023-07-19 um 22 51 06" src="https://github.com/gaseous-project/gaseous-server/assets/110769699/4b613581-9ec0-4ce5-b6f1-89e04ae37b0d">

**Comment by michael-j-green** [comment]
That's great to hear!

So, I think the issue here is a stale browser cache. Try clearing the cache. I think that should do it.

I'll need to add something to get the browser to throw away the cache during upgrades.

**Comment by FlorianH1989** [comment]
Yes, that was it. The Games can be played again. Thanks!

**Comment by michael-j-green** [comment]
This is the workflow I've been working on... each game page (including the "Unknown Game" title) will have an edit button above the ROM list:
<img width="1728" alt="Screenshot 2023-08-03 at 10 32 59 am" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/207a886c-ef09-42f4-9057-62f9e5c17ba6">

Once clicked, the edit button will display checkboxes and drop downs to change the game mapping for each ROM. The edit button will change to a Cancel button which will hide these checkboxes and buttons:
<img width="1728" alt="Screenshot 2023-08-03 at 10 33 09 am" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/7edde9fc-e6e6-414c-9946-bc23efadd437">

What do you think?

**Comment by michael-j-green** [comment]
Work flow complete! Updated page styling:
<img width="1728" alt="Screenshot 2023-08-03 at 4 58 09 pm" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/7f3add44-6e15-4138-9bdc-6de0761442ef">
<img width="1728" alt="Screenshot 2023-08-03 at 4 58 41 pm" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/84e84fe5-1e1a-497b-991c-2b24136d61c5">
<img width="1728" alt="Screenshot 2023-08-03 at 4 59 11 pm" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/2afb63a6-fc2d-4764-a2b6-39b47e288c74">
