### ISSUE TITLE
Make japanese console use the same emulators as the western counterparts.

### ISSUE THREAD

**Issue by mannysanch** [gaseous-project/gaseous-server#306]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have Family Computer, and Super Famicom, as well as any other applicable platforms (PC Engine?) use the cores for their western console counterparts, e.i. Famicom = NES, Super Famicom = SNES.

**Describe alternatives you've considered**

I tried exporting the platformmap.json and then reimporting it, but I've only managed to get it to recognize the extensions I've put in, not anything regarding the emulator to use.

**Additional context**
I've edited the platformmap Famicom section as follows:

>     "IGDBId": 99,
>     "IGDBName": "Family Computer",
>     "IGDBSlug": "famicom",
>     "AlternateNames": [
>       "Famicom"
>       "Nintendo Entertainment System",
>       "Nintendo Famicom & Entertainment System"
>     ],
>     "Extensions": {
>       "SupportedFileExtensions": [
>         ".7Z",
>         ".FDS",
>         ".NES",
>         ".NEZ",
>         ".UNF",
>         ".UNIF",
>         ".ZIP"
>       ],
>       "UniqueFileExtensions": [
>         ".FDS",
>         ".NES",
>         ".NEZ",
>         ".UNF",
>         ".UNIF"
>       ]
>     },
>     "RetroPieDirectoryName": "nes",
>     "WebEmulator": {
>       "Type": "EmulatorJS",
>       "Core": "nes",
>       "AvailableWebEmulators": [
>         {
>           "EmulatorType": "EmulatorJS",
>           "AvailableWebEmulatorCores": [
>             {
>               "Core": "nes",
>               "AlternateCoreName": "fceumm",
>               "Default": true
>             },
>             {
>               "Core": "nestopia",
>               "AlternateCoreName": "",
>               "Default": false

**Comment by michael-j-green** [comment]
Resolved in https://github.com/gaseous-project/gaseous-server/issues/315

See this comment for resolution: https://github.com/gaseous-project/gaseous-server/issues/315#issuecomment-1962788999
