### ISSUE TITLE
Update platformmap.json to provide emulators for Super Famicom and Famicom

### ISSUE THREAD

**Issue by michael-j-green** [gaseous-project/gaseous-server#315]
The emulators should be the SNES and NES ones respectively.

**Comment by michael-j-green** [comment]
Updated PlatformMap.json attached.

Import this file into 1.7.1 Gaseous or later to make the requested cores available.

Go to Settings -> Platform Mapping, then click "Import JSON"

[PlatformMap.json](https://github.com/gaseous-project/gaseous-server/files/14395030/PlatformMap.json)

**Comment by mannysanch** [comment]
Thank you.
