### ISSUE TITLE
Infinite Scrolling breaks clicking the Gaseous Games logo to return to library

### ISSUE THREAD

**Issue by chandz05** [gaseous-project/gaseous-server#316]
**Describe the bug**
Clicking the "Gaseous Games" logo on the top left when infinite scrolling is turned on doesn't result in expected behavior. It seems to try to produce some sort of paginated view with a limited number of games. The only way to to return to the expected view is to click the "reset" button in the filter. Clicking the browser's "reload" button does not return the view to normal.

**To Reproduce**
Scenario 1:
1. Go to "Profile" and enable Infinite Scrolling
2. On the main library page, scroll down a few pages
3. Click the "Gaseous Games" logo on the top left
4. Library does not return to first game

OR

Scenario 2:
1. Go to "Profile" and enable Infinite Scrolling
2. On the main library page, scroll down a few pages
3. Click on a game
4. Click the "Gaseous Games" logo on the top left
5. Library does not return to previous view

**Expected behavior**
Scenario 1: When the "Gaseous Games" logo is clicked, the library returns to to the first game.
Scenario 2: When the "Gaseous Games" logo is clicked, the library returns to the previous view (this expected behavior can be observed when clicking the "back" button on the browser)

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser Firefox V123.0 (64-bit)

**Comment by michael-j-green** [comment]
Closed in #326
