### ISSUE TITLE
Provide an option to hide or show the save file buttons in EJS

### ISSUE THREAD

**Issue by michael-j-green** [gaseous-project/gaseous-server#332]
The load/save file buttons were hidden in 1.7.2 to prevent confusion around the save options. However, some users use these to upload memory card save files.

An option should be added to the user prefs to hide or show these buttons (defaulting to hidden).

**Comment by colder1989** [comment]
Is it possible to insert this option? I have a lot of saves I would like to use

**Comment by Legomountain14** [comment]
Same here. I want to switch to gaseous from RetroArch, but I can't figure out how to import save files.

**Comment by michael-j-green** [comment]
> Same here. I want to switch to gaseous from RetroArch, but I can't figure out how to import save files.

Importing of save states is supported if you've got those. Otherwise, I'll add this request for the currently in development version.
