### ISSUE TITLE
Can't install with docker compose (MariaDB)

### ISSUE THREAD

**Issue by sergiohf** [gaseous-project/gaseous-server#380]
I have a CasaOS install within ubuntu 24.04. I have tried to install Gaseous from both the CasaOS installer and using docker compose using the docker-compose.yml that is in the github. With casaos i can install, but i receive connection refused error.  The logs shows a bunch of database errors. Trying to install using docker compose is useless, the errors appears before any instalation. Using the docker compose example from docker hub (which uses mysql) I can install and run normally the server from CasaOS. https://hub.docker.com/r/gaseousgames/gaseousserver

**Comment by michael-j-green** [comment]
I've updated the documentation on the docker hub page (thankyou for the reminder!).

I'm in the process of installing CasaOS at the moment (I've never used it before), so I'll reply to this issue with whatever I find.

**Comment by michael-j-green** [comment]
I've just completed an install of Gaseous on CasaOS without issue, using the MariaDB based docker-compose.yml file in the repo.

Note that on startup Gaseous reaches out to IGDB to pull metadata, and so can take a short period of time to start up.

Can you share the errors you were getting?

**Comment by michael-j-green** [comment]
I just found that CasaOS tries to be clever and put an app icon on the main screen. This icon is non-functional - I don't know why as I'm not familiar with what CasaOS is trying to do here. You should go directly to Gaseous, rather than trying to use the CasaOS icon.

**Comment by sergiohf** [comment]
The icon in CasaOs is functional, but you need to set the webui port to 5198. I also set the icon with the link: https://github.com/gaseous-project/gaseous-server/blob/main/logo.png?raw=true

As for the installation you are right, i needed to wait. This time worked, took almost 10 minutes, but worked.

Thanks for the quick response.
