### ISSUE TITLE
Super Famicom games do not launch

### ISSUE THREAD

**Issue by primetime00** [gaseous-project/gaseous-server#416]
**Describe the bug**
When adding a Super Famicom game, the game is correctly parsed and has proper images pulled.  However, when clicking on the title, there is no option to launch the title.  In settings, Super Famicom has no web emulator support, but shouldn't it just use the same snes9x core?

**To Reproduce**
Upload a Super Famicom title
Reload page
Select title

**Expected behavior**
The game should launch using the snes9x core in emulatorJS

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 127.0.6533

**Comment by michael-j-green** [comment]
Apologies. I thought I had deployed that fix already.

This can be fixed without downloading a new version of Gaseous - though I'll make sure this update is in the next version so you won't have to worry about it again.

1. Download the attached PlatformMap.json file: [PlatformMap.json](https://github.com/user-attachments/files/16882416/PlatformMap.json)
2. Go to Settings
3. Go to Platform Mapping
4. Click "Import JSON"
5. Select the above PlatformMap.json file

The file will be uploaded and the page should reload once complete.

If you then scroll down to Super Famicom, you should see that it now has an emulator core associated with it.

Let me know how you go.

**Comment by primetime00** [comment]
Thanks!  That fixed the issue!

**Comment by michael-j-green** [comment]
You're welcome!

I'm going to leave this issue open to remind me to make sure that this fix is in the final 1.8.0 build :D
