### ISSUE TITLE
Remove login requirement.

### ISSUE THREAD

**Issue by devanteweary** [gaseous-project/gaseous-server#440]
**Is your feature request related to a problem? Please describe.**
No problems.

**Describe the solution you'd like**
I just don't want a login page. 

**Describe alternatives you've considered**
Usernames instead of emails.

**Additional context**
Basically I like to have my own domain and put Gaseous available so I can go to games.mydomain.com and I can play anywhere. But also let my friends play so don't want to have to provide them each with emails/passwords. Especially the email part.

**Comment by michael-j-green** [comment]
Hi @devanteweary; disabling authentication and then putting the server on the open internet is a very very bad idea. As such I won't be providing the functionality to disable authentication.

What you could do as a work around is to create a single user account and share that with your friends. Checking the "Remember Me" box at logon will leave the session logged in - provided cookies aren't deleted and/or they sign in within 30 days of the last login, they won't get logged out.

I urge you to reconsider creating separate accounts (or at least using a lower permission account to share with your friends) as the Admin permission grants permission to delete ROMs, upload anything (if it's not a ROM, Gaseous will still store it and make it available under unknown title), not to mention that all users using the same login will be able to create or delete _any_ saved game states.

**Comment by devanteweary** [comment]
Thanks for the reply.  
I've considered all those scenarios and they aren't a problem, really.  
I just wanted a quick page I can go to or have a few friends go to to do some quick gaming.

I'm not trying to run a super gaming mega server, you know what I mean? 
It doesn't really matter if it's sharing save states, etc.

If I wanted it more serious, then I'd go ahead and do separate accounts.  
I have my own authentication before my pages anyway so now they have to log in twice.

Oh and if I'm correct, I still have to provide some kind of fake email address instead of something simple such as username: games when creating a shared account. It wouldn't be so bad if we could just use usernames instead of forced emails.

Anyway just something to consider I guess.  

Thanks for taking the time to read!

**Comment by michael-j-green** [comment]
If it helps, I do have OIDC support as a goal for the next version: https://github.com/gaseous-project/gaseous-server/issues/342

**Comment by michael-j-green** [comment]
Also; point taken with the username.

I'll add that, see: https://github.com/gaseous-project/gaseous-server/issues/441

**Comment by darylf** [comment]
I'd be interested in removing authentication too. Perhaps have auth on by default, and set a configuration flag to disable authentication?

In my case, it's only ever run locally by a single user (me).
