### ISSUE TITLE
Upload takes forever.

### ISSUE THREAD

**Issue by dibu28** [gaseous-project/gaseous-server#456]
**Describe the bug**
Upload takes forever.

**To Reproduce**
1. Go to Upload
2. Upload file or multiple files.
3. Upload progressbar moves to 100%
4. Nothing happen after it.

**Expected behavior**
ROMS Uploaded.

**Screenshots**
![image](https://github.com/user-attachments/assets/e545e7b4-1911-499e-80f2-5185f76e170f)

**Desktop (please complete the following information):**
 - OS: PROXMOX LXC Ubuntu Docker Compoes Container
 - Browser Chrome
 - Version latest

**Additional context**
I also see no platforms in the list:
"Override automatic platform detection:"
The list is just empty.

**Comment by michael-j-green** [comment]
If you go to Settings -> Platform Mapping, do you have platforms listed there?

**Comment by dibu28** [comment]
> If you go to Settings -> Platform Mapping, do you have platforms listed there?

It is Empty
![image](https://github.com/user-attachments/assets/db136ce3-753c-43b6-9a14-85e6ead2eed7)

**Comment by michael-j-green** [comment]
Have you added the IGDB credentials? This looks like it's unable to connect to IGDB to pull the required data.

**Comment by dibu28** [comment]
> Have you added the IGDB credentials? This looks like it's unable to connect to IGDB to pull the required data.

No

**Comment by michael-j-green** [comment]
No. IGDB credentials are required. See the installation instructions here: https://github.com/gaseous-project/gaseous-server/wiki/Installation
