### ISSUE TITLE
Support Signatures Redump

### ISSUE THREAD

**Issue by sandmaennchen5** [gaseous-project/gaseous-server#459]
(http://redump.org/downloads/)

**Comment by michael-j-green** [comment]
I had no idea this existed. Thank you for letting me know.

Do you know of other signature sources like this?

**Comment by michael-j-green** [comment]
Depends on: https://github.com/gaseous-project/gaseous-signature-parser/issues/11

**Comment by michael-j-green** [comment]
@sandmaennchen5; I've integrated Redump support into Hasheous, which is located at https://hasheous.org/

Would you be able to search for some MD5/SHA1 hashes, and verify the responses?

Once I hear back from you, I'll start integrating Redump support into v1.7.8.
