### ISSUE TITLE
Unable to import signatures 

### ISSUE THREAD

**Issue by IgorMonasterio** [gaseous-project/gaseous-server#460]
Hi there! Running this on a docker container in truenas scale. The server is running well, the only thing I can’t get to work are the signatures. Have all .dat in the mount folders as described in the instructions here, but apparently is not finding any. Anyone having the same issue?

**Comment by michael-j-green** [comment]
Would you be able to send the directory structure you've got for the `.gaseous-server/Data/Signatures` directory?

**Comment by IgorMonasterio** [comment]
Hi Michael! Right now looks like this. 
![IMG_0086](https://github.com/user-attachments/assets/bba76981-b4b1-4f5f-b6ed-b62bf837839d)

Inside each of these folders I tried to copy the files as they come after extracted, with all folders and everything, and also copying only the .dat files straight to there. In both cases no luck.

**Comment by michael-j-green** [comment]
I was referring to the filesystem; not the logs :)

But each one of those folders should contain only the `*.dat` files, and nothing else. Subdirectories aren't supported.

**Comment by IgorMonasterio** [comment]
Sorry. I’m a little bad with this things. Here are the screenshots from my mounting paths in the container. The roms one is working fine.

![IMG_0087](https://github.com/user-attachments/assets/d9c909e1-6f1a-4d1a-8a1c-27e534adf5fb)
![IMG_0088](https://github.com/user-attachments/assets/d7dce1a4-01fa-41d1-a1af-ded91ac80786)
![IMG_0089](https://github.com/user-attachments/assets/d712ee52-2217-4399-bc59-980e227194f4)
![IMG_0090](https://github.com/user-attachments/assets/ec7e37ff-fc19-4254-b0a6-41546e836421)

Now I have just .dat files straight to these folders. One .dat in mame arcade, one .dat in mame mess and a lot of .dat in tosec. When I click the green start button on signature import task, is not taking anything. It scans but instantly finishes. Thank you very much for your time and patience.

**Comment by IgorMonasterio** [comment]
I found the issue. Had the mount paths all wrong. Should be  /root/.gaseous-server/Data/Signatures/TOSEC instead of  /.gaseous-server/Data/Signatures/TOSEC. Missing the /root/ at the beginning in all 3 folders

**Comment by michael-j-green** [comment]
Awesome! Glad it's working :)
