### ISSUE TITLE
Emailaddress and password after setup

### ISSUE THREAD

**Issue by dot19408** [gaseous-project/gaseous-server#463]
**Describe the bug**
After spinning up the docker-compose and connecting to gasious-server it asks for an email address and password.

No emailaddress or password has yet been configured, and none I tray are accepted.

**To Reproduce**
1. Spin-up the docker instance
2. navigate to the URL
3. asked for email and password
4. ??? where was/is this set?

**Expected behavior**
Prompt to create a user account

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, Chrome, Edge
 - Version Latest as of 12/8/2024

**Comment by michael-j-green** [comment]
This bug has reared it's ugly head again... for some reason, for some users, Gaseous thinks it's first run wizard has already been run when it hasn't actually done that - so they get a prompt for a user account that's not been created.

Try navigating to `http://<host>:<port>/pages/first.html` and let me know how you go. You should see a form asking for you to create an account.

**Comment by dot19408** [comment]
Sweet! That took care of it.

Thank you!
