### ISSUE TITLE
Update not working after edit

### ISSUE THREAD

**Issue by Flyingfufu** [gaseous-project/gaseous-server#51]
**Describe the bug**
When editing a title through the "edit" button feature, nothing happen after hitting "update"

**To Reproduce**
1. Go to 'any title'
2. Click on 'Edit'
3. Edit the platform or title
4. Click on 'Update'

**Expected behavior**
Information are updating and we come back to the title screen.

**Additional context**
Running on docker

**Comment by michael-j-green** [comment]
Yup... this one's on me. I neglected to put progress status, and refresh the screen once the update is complete.

The changes you made in the update should have completed successfully, just the UI didn't tell you as much. Until I get a fix out (which hopefully should be either today or tomorrow), simply refreshing the page should resolve the issue.

**Comment by michael-j-green** [comment]
One of the biggest issues with the bulk updater is that in the currently released version (v1.4.0), when new game metadata is required - it pulls all the metadata for that game from IGDB. This is slow. Very slow.

v1.5.0 removes this, and just grabs the most basic metadata and the cover art - the rest is pulled as needed, or on the next metadata refresh.

**Comment by michael-j-green** [comment]
I've just pushed version v1.4.1, which should resolve the issue. Would you be able to test it and let me know how it goes?

**Comment by michael-j-green** [comment]
BTW: you may need to empty your browser cache after pulling the latest update

**Comment by Flyingfufu** [comment]
Thanks for the feedback and quick action.

Initially I thought it doesn't work, until I've realized that before hitting "update" I have to tick the selection box (not obvious when the title appear only for 1 platform). Once done properly, it works like a charm !

BTW, great work. I like it much !
