### ISSUE TITLE
Update PlatformMap.json to include more (and correct) known file extensions

### ISSUE THREAD

**Issue by michael-j-green** [gaseous-project/gaseous-server#66]
See discussion in #64.

Possible source for extension mapping: https://emulation.gametechwiki.com/index.php/List_of_filetypes

**Comment by Flyingfufu** [comment]
additional interesting link :
https://retropie.org.uk/docs/Supported-Systems/
https://www.file-extensions.org/filetype/extension/name/emulator-files

**Comment by michael-j-green** [comment]
Should be resolved in v1.4.2

**Comment by michael-j-green** [comment]
Would you be able to confirm if it's working? Thanks!

**Comment by michael-j-green** [comment]
Confirmed working with @Flyingfufu on Discord. Closing.
